name: Continuous Integration

on:
  push:
  workflow_dispatch:

jobs:
  execute_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17 for SDK Manager
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install Appium
        run: |
          npm install -g appium

      - name: Install UiAutomator2
        run: |
          appium driver install uiautomator2

      - name: Start up Appium
        run: |
          nohup appium -p 4723 -pa /wd/hub &

      - name: Install Android SDK system image
        run: |
          sdkmanager --install "system-images;android-29;google_apis;x86_64"

      - name: Create Device
        run: |
          echo no | avdmanager create avd -n "Pixel_4_API_29" -k "system-images;android-29;google_apis;x86_64" -d pixel_4

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      # Adicionando espera para o emulador iniciar completamente
      - name: Wait for Emulator to Start
        run: |
          sleep 60 # Aguarda 60 segundos para garantir que o emulador foi iniciado

      - name: Run Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          profile: pixel_4
          script: |
            avdmanager list device
            mvn clean install -DAPPIUM_PORT=4723 .
        # Adicionando a flag para não matar automaticamente o emulador após o teste
        avd-runner-options: '--no-kill'

      # Adicionando a variável de ambiente para aumentar o tempo de espera antes de matar o emulador
      - name: Set environment variable for emulator kill delay
        run: |
          echo "ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL=60" >> $GITHUB_ENV

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            target/surefire-reports/
            target/cucumber-reports/
